### ISSUE TITLE
'Uncaught SyntaxError: Unexpected end of JSON input' upon installing Colada

### ISSUE THREAD

**Issue by redfox05** [oslabs-beta/colada#59]
## Issue
After following the install instructions to add Colada to our project, running the web application results in two JSON parse errors, as shown below:

```
VM290:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at colada-plugin.esm-browser.js:2985:1

VM292:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at saveMessage (content-script.js:3:58)
```

## Steps to reproduce
1. Add Pinia to the project, and start setting up reactive stores.
2. No issues so far.
3. Follow instructions at https://colada.dev/#install to add Colada.
4. Load the app in browser (Chrome  117.0.5938.62).
5. Check Dev Console. Issues displayed as detailed above. 

## Steps tried so far:
At first, I thought it was linked to the Pinia store code, and maybe there was an issue there, but I went through the code and commented out all references and imports for the reactive stores. So now all that remains is the init code for Pinia and Colada (the app.use etc).

## Versions:
vue: 3.3.4
pinia: 2.1.6
colada-plugin: 0.1.0

**Comment by redfox05** [comment]
Can confirm that after removing all the Colada code from our project (As this was blocking our work), the issue is still present, and finally only went away after removing the Chrome Colada extension. So it must be something in the extension code. Will have to just rely on the basic pinia integration into the Vue dev tools for now, as Colada does not seem to be working.

Sadly none of the other issues reported here seem to be getting replies, so maybe this issue will not be resolved anytime soon, but here's hoping, and hopefully this helps anyone else who comes across this problem.
